services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - urlshortener-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - urlshortener-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - urlshortener-network

networks:
  urlshortener-network:
    driver: bridge