spring.application.name=urlshortener

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}